---
- name: Downloading phplist
  get_url: 
    url: 'http://heanet.dl.sourceforge.net/project/phplist/phplist/{{ phplist_version }}/phplist-{{ phplist_version }}.tgz'
    dest: /tmp/

- name: Ensuring phplist is installed
  unarchive: 
    src: '/tmp/phplist-{{ phplist_version }}.tgz'
    dest: '{{ phplist_path }}'
    extra_opts: ['--strip-components=1', '--show-stored-names']
    #extra_opts: ['--strip-components=1']
    remote_src: yes
  args:
    creates: '{{ phplist_path }}/bin/phplist'

- name: Ensuring phplist is configured
  lineinfile:
    dest: '{{ phplist_path }}/public_html/lists/config/config.php'
    line: '{{ item.line }}'
    regexp: '{{ item.regexp }}'
    backrefs: yes
  with_items:
    - { regexp: "^(.*)database_host =(.*)'",                  line: "$database_host = '{{ phplist_database_host }}';" }
    - { regexp: "^(.*)database_name =(.*)'",                  line: "$database_name = '{{ phplist_database_name }}';" }
    - { regexp: "^(.*)database_user =(.*)'",                  line: "$database_user = '{{ phplist_database_user }}';" }
    - { regexp: "^(.*)database_password =(.*)'",              line: "$database_password = '{{ phplist_database_password }}';" }

- name: Change mattermost directory permissions
  file:
    path: '{{ phplist_path }}/public_html/lists/admin/plugins'
    state: directory
    owner: "{{ phplist_user }}"
    group: "{{ phplist_user }}"
    recurse: yes

