---
- name: Download binary from MatterMost website
  get_url: 
    url: http://heanet.dl.sourceforge.net/project/phplist/phplist/{{ phplist_version }}/phplist-{{ phplist_version }}.tgz
    dest: /tmp/

- name: unpack mattermost archive
  unarchive: 
    src: /tmp/phplist-{{ phplist_version }}.tgz 
    dest: /opt/
    copy: no
  args:
    #creates: /opt/mattermost/bin/platform

#- name: Listen on public and private IP
#  lineinfile:
#    dest: /opt/mattermost/config/config.json
#    line: '{{ item.line }}'
#    regexp: '{{ item.regexp }}'
#    backrefs: yes
#  with_items:
#    - { regexp: '"SiteURL":',                  line: '        "SiteURL": "{{ mattermost_config.SiteURL }}",' }
#    - { regexp: '"DataSource":',               line: '        "DataSource": "{{ mattermost_db_user }}:{{ mattermost_db_password }}@tcp(127.0.0.1:3306)/{{ mattermost_db_name }}?charset=utf8mb4,utf8",' }

#- name: Change mattermost directory permissions
#  file:
#    path: /opt/mattermost
#    state: directory
#    owner: "{{ mattermost_user }}"
#    group: "{{ mattermost_user }}"
#    recurse: yes

